# Generated by Django 4.1 on 2023-11-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='uname',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
