# Generated by Django 4.1 on 2023-11-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_customers_uname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='uname',
            new_name='username',
        ),
    ]
