# Generated by Django 4.1 on 2023-11-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_customers_password_remove_customers_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='email',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
