# Generated by Django 4.1 on 2023-12-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='app1.genre'),
        ),
    ]
